services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - ${RUSTFS_ENDPOINT_PORT} 
      - ${RUSTFS_ENDPOINT_PORTS} 
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
    volumes:
      - rustfs_data:/data
    command: server /data --console-address ":${RUSTFS_CONSOLE_PORT}"

volumes:
  rustfs_data: